### ISSUE TITLE
Subtitle support

### ISSUE THREAD

**Issue by frazse** [luksus42/plex-app#6]
Any plans on adding subtitle support?
This is kinda needed for watching anime etc.

**Comment by luksus42** [comment]
Yes, I was thinking about it.
Now, if there seems to be a demand for it, I will check if I can add this feature to the player.

**Comment by luksus42** [comment]
I just added initital support for subtitles...
The plex-server needs to reencode the file, to "burn" the subtitles in the movie.
What is not working, is fast switching between subtitles, because of the reencode. I needed to stop playback for some minutes, and sometimes to reload the app, because the old stream, with the other subtitle was cached somewhere...
